### ISSUE TITLE
Not working action paths like test/:id

### ISSUE THREAD

**Issue by mstn** [unmonastery/untransit#1]
See issue https://github.com/chaplinjs/chaplin-boilerplate-plain/issues/14

**Comment by mstn** [comment]
@fvitullo has kindly refactored the code for express (thanks!). See https://github.com/unmonastery/untransit/pull/6

We should give a try to setup action paths with express.

**Comment by cdbkr** [comment]
Hiya!! Actually, Im looking for a proper and clean solution to solve this case.
Any suggest?

**Comment by mstn** [comment]
@fvitullo sorry for late reply. I do not know express very well. However, I think the trick is to point 404 to index.html.

@elf-pavlik I saw you used nginx on the "production" server. You should do the same also for nginx, I suppose.

**Comment by mstn** [comment]
example of express with pushstate
http://heu.io/posts/push-state-with-nodejs-and-express/

**Comment by mstn** [comment]
I solved the problem. Quite stupid mistake, I used wrong urls with ./ instead of /
