### ISSUE TITLE
Testing Matera data on a different branch

### ISSUE THREAD

**Issue by mstn** [unmonastery/untransit#10]
- [ ] create a different branch for testing Matera gtfs
- [ ] Import fresh gtfs data for Matera.
- [ ] Change UI in order to make clear where data are missing/incomplete
- [ ] add Matera gtfs to gitignore

**Comment by elf-pavlik** [comment]
@mstn @fvitullo let's please stop commiting gtfs data to this repo! maybe we can use submodules instead? or just grunt task to fetch it while keeping it in .gitignore

**Comment by cdbkr** [comment]
@elf-pavlik  Sorry about that. I was trying that and thought it could be useful to push the changes, but you are right.
Are you ok with adding the submodule to public/data/matera and using https://www.npmjs.org/package/grunt-update-submodules ?

**Comment by elf-pavlik** [comment]
@fvitullo sounds good to me! if you make pull request for that i'll merge it :smile:

**Comment by mstn** [comment]
Sorry I didn't write a clear description for this task (just edited). I was going to work on a different branch in order to see what Matera gtfs looks like now and improving ui a bit. I agree with @fvitullo grunt+submodule is good (I'll create a different issue). We could integrate scripts we did for exporting data from OSM as a kind of library.

**Comment by mstn** [comment]
@elf-pavlik @fvitullo I propose as a general rule one should assign a task to him/herself if (s)he is going to work on it. In this way we should be able to avoid to overlap. Moreover, please add a issue for whatever you want to do in this way the others can keep track of what is happening.

**Comment by cdbkr** [comment]
Added CONTRIBUTING.md to latest Pull Request so we can define general rules for contributing.

**Comment by elf-pavlik** [comment]
@mstn can we close this one since i merged #13 ?
