### ISSUE TITLE
Add gtfs data as submodules

### ISSUE THREAD

**Issue by mstn** [unmonastery/untransit#12]
Gtfs data should be gitignored. I think the only exception could be Pavia data just because they are our "test" data.

As proposed by @fvitullo in #10, we could use grunt+submodules. We could integrate this script https://github.com/unmonastery/GtfsMaker in such a way that gtfs are built dynamically from OSM and Miccolis timetables.

**Comment by elf-pavlik** [comment]
@mstn I started rewriting https://github.com/unmonastery/GtfsMaker to use Grunt and builder scripts, we could release them later to npm!

for now i think we can live with those 3 separate repositories since once we get all data in OSM we shouldn't need to regenerate gtfs files very often...

**Comment by cdbkr** [comment]
@mstn @elf-pavlik I just pulled a request for data as submodules. Please, if you have any suggest don't hesitate to share it. At the moment the grunt task is just updating the submodules in the project. If we want to support grunt tasks inside submodules too we can add grunt-submodules module to execute every relative grunt task in.

**Comment by elf-pavlik** [comment]
closed via #13, THX @fvitullo :exclamation:
