### ISSUE TITLE
add .editorconfig

### ISSUE THREAD

**Issue by elf-pavlik** [unmonastery/untransit#14]
http://editorconfig.org/

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

**Comment by mstn** [comment]
For Atom (my editor), there is a plugin https://github.com/sindresorhus/atom-editorconfig :+1:

**Comment by elf-pavlik** [comment]
first version here: https://github.com/unmonastery/untransit/blob/editorconfig/.editorconfig
i would like to also reformat all existing files accordingly if no one has anything pending to merge!

**Comment by elf-pavlik** [comment]
done in 62622f3

@fvitullo could you please enable plugin in your editor - http://editorconfig.org/#download

**Comment by cdbkr** [comment]
Thanks! I will update my IDEs to support editorconfig ;)
